mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.entity
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
    maxActive: 50
    maxIdle: 5
    minIdle: 0
    initialSize: 0
    filters: stat,wall,log4j
    validation-query: select 1
    test-on-borrow: true
  redis:
    host:
    port: 6379
    password:
    ettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
      timeout: 5000